name: Get latest blogs from sitemap

on:
  schedule:
    - cron: '0 0 * * 0' 
  workflow_dispatch:

jobs:
  get-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Download sitemap
        run: curl -s -o sitemap.xml https://sahill17.github.io/sitemap.xml

      - name: Extract & build Markdown links
        run: |
          # Extract all <loc> entries, one per line
          xmllint --xpath "//*[local-name()='loc']/text()" sitemap.xml \
            | tr ' ' '\n' \
            | grep -E '^https://sahill17\.github\.io/post/[^/]+/?$' \
            > urls.txt

          # Build markdown list items from the first 5 URLs
          LINKS=$(head -n 5 urls.txt \
            | sed -E 's|https://sahill17\.github\.io/post/([^/]+)/?$|- [\1](https://sahill17.github.io/post/\1)|')

          # Export LINKS as an environment variable for the next step
          echo "LINKS<<EOF" >> $GITHUB_ENV
          echo "$LINKS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          FILE="README.md"
          START="<!-- BlogPosts:START -->"
          END="<!-- BlogPosts:END -->"

          # Use the LINKS env var
          awk -v start="$START" -v end="$END" -v links="$LINKS" '
            $0 ~ start { print; print links; inBlock=1; next }
            $0 ~ end   { inBlock=0; print; next }
            !inBlock   { print }
          ' "$FILE" > tmp && mv tmp "$FILE"

      - name: Commit and push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          git add README.md
          if git diff --cached --quiet; then
            echo "No README changes to commit."
          else
            git commit -m "chore: update latest blog posts"
            git push
          fi
